travis:
  secure:
    BINSTAR_TOKEN: b3kGgBZd4PpEKD3Sn5Tq6UMP4EvRcpmRLsL4oehTztCfGUae5EfI1JoGLbR9lg8JbgXPO0gJ1YPLQp9qtrN16VxP6mqburhIC/eQSb9cXLvhbSjJB6AqqJkGOH1WR2AGI0KwfpxKEJwhGAxPPEkfS8N0b2T3buZ0HjQOBkySQvMVHbHgHwXnnsnmF0japYt6FFf8QP8oa08HNcl5wH3ZfNeKjgXlZJWQ5bgmiSBlD9XCpxIJ7najw4pIvq2DN/PsMLGVVF68FtH6lsH3nAdpw48i7eE3sGWszDWcCvGmQbVNxWSXegyQUcBXD19vM0pXJV+nOJ/X5xQ30m5XKAmbS013sxGk5rznqf6nBuuS1AKT48zMI+34Yekl1Dnj9DFXBBL7J2k9zcHyrPnUrX+iX7wCBjiWCyQwb1kSmQf9vlxH99B4wDGUC9q2kmfmJ+gPXaY4FOflfS7AFYSJt7e9HjMybYPZe6sp40krrwVnACrbkz7jjw+OokUrqCn3E94b6Gfeoj6Yuy8GVqNka54EuJgonS7vodOUOQzHrK/GEQ7p2vVhab/vltO2gW+nZbLk0SEATzPNu3BCHBhalBmIiZ8bA/YBofRlbf3ibcpUVcNvI1hxvxRFtmnlfaAQgaDrV84+onCvIzrJNBBhORok970bVhiAFmwAsneQufD4ThA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
